Repository Adrian-Moreira/PlanPals, pull requests merged in 2024-11, with the labels that each got.

#72 Deletion middleware
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  package-lock.json
  package.json
  planner-service/__tests__/integration/activity-routes.test.ts
  planner-service/__tests__/integration/comment-routes.test.ts
  planner-service/__tests__/integration/d9n-routes.test.ts
  planner-service/__tests__/integration/planner-routes.test.ts
  planner-service/__tests__/unit/activity/activity-deleteActivity.spec.ts
  planner-service/__tests__/unit/comment/comment-removeCommentDocument.spec.ts
  planner-service/__tests__/unit/destination/d9n-deleteD9n.spec.ts
  planner-service/__tests__/unit/planner/planner-deletePlanner.spec.ts
  planner-service/src/models/Accommodation.ts
  planner-service/src/models/Activity.ts
  planner-service/src/models/Comment.ts
  planner-service/src/models/Destination.ts
  planner-service/src/models/Planner.ts
  planner-service/src/models/Transport.ts
  planner-service/src/services/accommodation.ts
  planner-service/src/services/activity.ts
  planner-service/src/services/comment.ts
  planner-service/src/services/destination.ts
  planner-service/src/services/planner.ts
  planner-service/src/services/transportation.ts
Labels: bug

#73 Android vote
  front-end-android/planpals/.dart_tool/dartpad/web_plugin_registrant.dart
  front-end-android/planpals/.dart_tool/package_config.json
  front-end-android/planpals/.dart_tool/package_config_subset
  front-end-android/planpals/.dart_tool/version
  front-end-android/planpals/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
  front-end-android/planpals/android/local.properties
  front-end-android/planpals/ios/Flutter/Generated.xcconfig
  front-end-android/planpals/ios/Flutter/flutter_export_environment.sh
  front-end-android/planpals/ios/Runner/GeneratedPluginRegistrant.h
  front-end-android/planpals/ios/Runner/GeneratedPluginRegistrant.m
  front-end-android/planpals/macos/Flutter/ephemeral/Flutter-Generated.xcconfig
  front-end-android/planpals/macos/Flutter/ephemeral/flutter_export_environment.sh
  front-end-flutter/planpals/lib/comment_page.dart
  front-end-flutter/planpals/lib/destination_test.dart
  front-end-flutter/planpals/lib/features/profile/viewmodels/user_viewmodel.dart
  front-end-flutter/planpals/lib/features/profile/views/login_page.dart
  front-end-flutter/planpals/lib/features/profile/views/signup_page.dart
  front-end-flutter/planpals/lib/features/travel_planner/models/accommodation_model.dart
  front-end-flutter/planpals/lib/features/travel_planner/models/activity_model.dart
  front-end-flutter/planpals/lib/features/travel_planner/models/destination_model.dart
  front-end-flutter/planpals/lib/features/travel_planner/models/transport_model.dart
  front-end-flutter/planpals/lib/features/travel_planner/services/planner_service.dart
  front-end-flutter/planpals/lib/features/travel_planner/viewmodels/planner_viewmodel.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_accommodation_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_activity_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_destination_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_planner_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_transport_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/update/update_accommodation_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/update/update_activity_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/update/update_destination_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/update/update_transport_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/accommodation_card.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/activity_card.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/destination_card.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/transport_card.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/planner_details_view.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/planners_view.dart
  front-end-flutter/planpals/lib/features/vote/vote_model.dart
  front-end-flutter/planpals/lib/features/vote/vote_service.dart
  front-end-flutter/planpals/lib/features/vote/vote_viewmodel.dart
  front-end-flutter/planpals/lib/main.dart
  front-end-flutter/planpals/lib/mockdb.dart
  front-end-flutter/planpals/lib/shared/components/generic_card.dart
  front-end-flutter/planpals/lib/shared/constants/constants.dart
  front-end-flutter/planpals/lib/shared/models/vote_model.dart
  front-end-flutter/planpals/lib/shared/network/api_service.dart
Labels: Task, User Story

#71 Updated Planner List UI
  front-end-web/src/App.css
  front-end-web/src/pages/planners.js
Labels: enhancement, Feature

#74 Implemented transportation on web planner page
  front-end-web/src/pages/planner.js
Labels: Task, User Story

#77 Web planner accommodations and activities
  front-end-web/src/pages/planner.js
Labels: Task, User Story

#79 Android comments
  front-end-flutter/planpals/lib/comment_page.dart
  front-end-flutter/planpals/lib/features/comment/comment_model.dart
  front-end-flutter/planpals/lib/features/comment/comment_page_view.dart
  front-end-flutter/planpals/lib/features/comment/comment_service.dart
  front-end-flutter/planpals/lib/features/comment/comment_viewmodel.dart
  front-end-flutter/planpals/lib/features/profile/services/user_service.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/destination_card.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/transport_card.dart
  front-end-flutter/planpals/lib/features/vote/vote_viewmodel.dart
  front-end-flutter/planpals/lib/main.dart
  front-end-flutter/planpals/lib/mockdb.dart
  front-end-flutter/planpals/lib/shared/components/generic_card.dart
  front-end-flutter/planpals/lib/shared/models/comment_model.dart
  front-end-flutter/planpals/lib/shared/network/api_service.dart
  front-end-flutter/pp_service_kit/.dart_tool/extension_discovery/devtools.json
  front-end-flutter/pp_service_kit/.dart_tool/extension_discovery/vs_code.json
  front-end-flutter/pp_service_kit/.dart_tool/package_config.json
  front-end-flutter/pp_service_kit/pubspec.lock
Labels: Task, Feature

#88 WebSockets
  backend/planner-ws/.gitignore
  backend/planner-ws/README.md
  backend/planner-ws/deno.json
  backend/planner-ws/src/data/clients.ts
  backend/planner-ws/src/data/queue.ts
  backend/planner-ws/src/data/topic.ts
  backend/planner-ws/src/main.ts
  backend/planner-ws/src/network/broadcast.ts
  backend/planner-ws/src/network/rabbit.ts
  backend/planner-ws/src/network/subscription.ts
  backend/planner-ws/src/network/websocket.ts
  backend/planner-ws/src/utils/args.ts
  backend/planner-ws/src/utils/info.ts
  backend/planner-ws/src/utils/signalListeners.ts
Labels: documentation
