Repository Adrian-Moreira/PlanPals, pull requests merged in 2024-10, with the labels that each got.

#9 Created web front end
  front-end-web/.gitignore
  front-end-web/README.md
  front-end-web/package-lock.json
  front-end-web/package.json
  front-end-web/public/PlanPals logo.jpg
  front-end-web/public/favicon.ico
  front-end-web/public/index.html
  front-end-web/public/logo192.png
  front-end-web/public/logo512.png
  front-end-web/public/manifest.json
  front-end-web/public/robots.txt
  front-end-web/src/App.css
  front-end-web/src/App.js
  front-end-web/src/App.test.js
  front-end-web/src/components/Navbar/NavbarElements.js
  front-end-web/src/components/Navbar/index.js
  front-end-web/src/index.css
  front-end-web/src/index.js
  front-end-web/src/pages/about.js
  front-end-web/src/pages/index.js
  front-end-web/src/reportWebVitals.js
  front-end-web/src/setupTests.js
Labels: Task

#28 Updated endpoints
  .vscode/settings.json
  front-end-web/package-lock.json
  front-end-web/package.json
  package.json
  planner-service/__tests__/commentController.test.ts
  planner-service/__tests__/planner-routes.test.ts
  planner-service/__tests__/user-routes.test.ts
  planner-service/package-lock.json
  planner-service/package.json
  planner-service/src/app.ts
  planner-service/src/controllers/accommodationController.ts
  planner-service/src/controllers/activityController.ts
  planner-service/src/controllers/commentController.ts
  planner-service/src/controllers/destinationController.ts
  planner-service/src/controllers/locationController.ts
  planner-service/src/controllers/plannerController.ts
  planner-service/src/controllers/transportationController.ts
  planner-service/src/controllers/userController.ts
  planner-service/src/controllers/votingController.ts
  planner-service/src/exceptions/MalformedRequestException.ts
  planner-service/src/exceptions/RecordConflictException.ts
  planner-service/src/models/Accommodation.ts
  planner-service/src/models/Activity.ts
  planner-service/src/models/Comment.ts
  planner-service/src/models/Destination.ts
  planner-service/src/models/Location.ts
  planner-service/src/models/Planner.ts
  planner-service/src/models/Transport.ts
  planner-service/src/models/User.ts
  planner-service/src/models/Vote.ts
  planner-service/src/routes/accommodationService.ts
  planner-service/src/routes/activity.ts
  planner-service/src/routes/comment.ts
  planner-service/src/routes/destination.ts
  planner-service/src/routes/location.ts
  planner-service/src/routes/planner.ts
  planner-service/src/routes/planner/destination/accommodation.ts
  planner-service/src/routes/planner/destination/activity/activity.ts
  planner-service/src/routes/planner/destination/activity/comment.ts
  planner-service/src/routes/planner/destination/activity/location.ts
  planner-service/src/routes/planner/destination/activity/vote.ts
  planner-service/src/routes/planner/destination/destination.ts
  planner-service/src/routes/planner/planner.ts
  planner-service/src/routes/planner/transportation/transportation.ts
  planner-service/src/routes/routers.ts
  planner-service/src/routes/transportation.ts
  planner-service/src/routes/user.ts
  planner-service/src/routes/vote.ts
  planner-service/src/services/CommentService.ts
  planner-service/src/services/PlannerServices.ts
  planner-service/src/services/accommodationService.ts
  planner-service/src/services/activityService.ts
  planner-service/src/services/commentService.ts
  planner-service/src/services/destinationService.ts
  planner-service/src/services/locationService.ts
  planner-service/src/services/plannerService.ts
  planner-service/src/services/transportationService.ts
  planner-service/src/services/userService.ts
  planner-service/src/services/votingService.ts
Labels: Task

#54 Android flutter to main
  docs/sprint0/Worksheet.md
  front-end-flutter/planpals/.gitignore
  front-end-flutter/planpals/ios/Runner.xcworkspace/contents.xcworkspacedata
  front-end-flutter/planpals/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  front-end-flutter/planpals/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  front-end-flutter/planpals/lib/destination_test.dart
  front-end-flutter/planpals/lib/features/home/views/home_page.dart
  front-end-flutter/planpals/lib/features/profile/services/user_service.dart
  front-end-flutter/planpals/lib/features/profile/viewmodels/user_viewmodel.dart
  front-end-flutter/planpals/lib/features/profile/views/login_page.dart
  front-end-flutter/planpals/lib/features/profile/views/signup_page.dart
  front-end-flutter/planpals/lib/features/travel_planner/models/accommodation_model.dart
  front-end-flutter/planpals/lib/features/travel_planner/models/activity_model.dart
  front-end-flutter/planpals/lib/features/travel_planner/models/destination_model.dart
  front-end-flutter/planpals/lib/features/travel_planner/models/planner_model.dart
  front-end-flutter/planpals/lib/features/travel_planner/models/transport_model.dart
  front-end-flutter/planpals/lib/features/travel_planner/services/planner_service.dart
  front-end-flutter/planpals/lib/features/travel_planner/viewmodels/planner_viewmodel.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_accommodation_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_activity_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_destination_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_planner_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_transport_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/update/update_accommodation_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/update/update_activity_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/update/update_destination_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/update/update_transport_form.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/accommodation_card.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/activity_card.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/destination_card.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/components/cards/transport_card.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/planner_details_view.dart
  front-end-flutter/planpals/lib/features/travel_planner/views/planners_view.dart
  front-end-flutter/planpals/lib/main.dart
  front-end-flutter/planpals/lib/mockdb.dart
  front-end-flutter/planpals/lib/shared/components/date_time_form.dart
  front-end-flutter/planpals/lib/shared/components/delete_message.dart
  front-end-flutter/planpals/lib/shared/components/generic_list_view.dart
  front-end-flutter/planpals/lib/shared/components/invite_user_dialog.dart
  front-end-flutter/planpals/lib/shared/constants/constants.dart
  front-end-flutter/planpals/lib/shared/network/api_service.dart
  front-end-flutter/planpals/lib/shared/utils/date_utils.dart
  front-end-flutter/planpals/macos/Flutter/GeneratedPluginRegistrant.swift
  front-end-flutter/planpals/macos/Runner.xcworkspace/contents.xcworkspacedata
  front-end-flutter/planpals/macos/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  front-end-flutter/planpals/pubspec.lock
  front-end-flutter/planpals/pubspec.yaml
  front-end-flutter/planpals/test/widget_test.dart
  front-end-flutter/planpals/web/manifest.json
Labels: Task, Feature

#60 Update README.md
  planner-service/docs/README.md
Labels: documentation

#67 New Destination UI
  front-end-web/src/App.css
  front-end-web/src/pages/planner.js
Labels: enhancement
