Repository Adrian-Moreira/PlanPals, pull requests merged in 2024-12, with the labels that each got.

#103 Shopping list UI react
  frontend/web-frontend/src/App.jsx
  frontend/web-frontend/src/Routes.jsx
  frontend/web-frontend/src/components/AppBar.tsx
  frontend/web-frontend/src/components/ShoppingLists/ItemCreate.tsx
  frontend/web-frontend/src/components/ShoppingLists/ShoppingList.tsx
  frontend/web-frontend/src/components/ShoppingLists/ShoppingListCard.tsx
  frontend/web-frontend/src/components/ShoppingLists/ShoppingListCreateView.tsx
  frontend/web-frontend/src/components/ShoppingLists/ShoppingLists.tsx
  frontend/web-frontend/src/containers/ShoppingListDetail.jsx
  frontend/web-frontend/src/containers/ShoppingLists.jsx
  frontend/web-frontend/src/lib/wsLib.ts
Labels: Feature

#106 Updated tests
  backend/planner-service/__tests__/unit/todoList/todoList-createTodoList.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-createTodoTask.spec.ts
Labels: bug

#107 Todo list backend
  backend/planner-service/__tests__/unit/todoList/todoList-createTodoList.spec.ts
  backend/planner-service/__tests__/unit/todoList/todoList-deleteTodoList.spec.ts
  backend/planner-service/__tests__/unit/todoList/todoList-getTodoList.spec.ts
  backend/planner-service/__tests__/unit/todoList/todoList-getTodoLists.spec.ts
  backend/planner-service/__tests__/unit/todoList/todoList-updateTodoList.spec.ts
  backend/planner-service/__tests__/unit/todoList/todoList-verifyTodoListPerm.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-createTodoTask.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-deleteTodoTask.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-getTodoTask.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-getTodoTasks.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-updateTodoTask.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-verifyTodoTask.spec.ts
  backend/planner-service/docs/README.md
  backend/planner-service/package-lock.json
  backend/planner-service/src/controllers/todoList.ts
  backend/planner-service/src/controllers/todoTask.ts
  backend/planner-service/src/models/TodoList.ts
  backend/planner-service/src/models/TodoTask.ts
  backend/planner-service/src/routes/routers.ts
  backend/planner-service/src/routes/todoList/todoList.ts
  backend/planner-service/src/routes/todoList/todoTask.ts
  backend/planner-service/src/services/todoList.ts
  backend/planner-service/src/services/todoTask.ts
Labels: Feature

#105 Shopping list flutter
  frontend/front-end-flutter/planpals/lib/features/home/views/home_page.dart
  frontend/front-end-flutter/planpals/lib/features/profile/viewmodels/user_viewmodel.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/Shopping_list_service.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/components/create_shopping_item_form.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/components/create_shopping_list_form.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/components/shopping_item_card.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/components/shopping_list_card.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/models/shopping_item_model.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/models/shopping_list_model.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/shopping_list_viewmodel.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/views/shopping_list_details_view.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/views/shopping_lists_view.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/services/planner_service.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/viewmodels/planner_viewmodel.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/views/planner_details_view.dart
  frontend/front-end-flutter/planpals/lib/main.dart
  frontend/front-end-flutter/planpals/lib/shared/components/generic_card.dart
  frontend/front-end-flutter/planpals/lib/shared/components/generic_list_view.dart
  frontend/front-end-flutter/planpals/lib/shared/components/invite_user_dialog.dart
  frontend/front-end-flutter/planpals/lib/shared/constants/constants.dart
  frontend/front-end-flutter/planpals/lib/shared/network/api_service.dart
Labels: Task, Feature

#108 Shopping list react fixes
  frontend/web-frontend/src/components/ShoppingLists/ShoppingList.tsx
  frontend/web-frontend/src/components/ShoppingLists/ShoppingListCreateView.tsx
  frontend/web-frontend/src/components/ShoppingLists/ShoppingListEditView.tsx
  frontend/web-frontend/src/components/ShoppingLists/ShoppingLists.tsx
Labels: enhancement

#111 Todo list flutter
  .vscode/settings.json
  backend/planner-service/__tests__/integration/todoList-routes.test.ts
  backend/planner-service/__tests__/integration/todoTask-routes.test.ts
  backend/planner-service/__tests__/unit/todoList/todoList-deleteTodoList.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-createTodoTask.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-deleteTodoTask.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-getTodoTasks.spec.ts
  backend/planner-service/__tests__/unit/todoTask/todoTask-verifyTodoTask.spec.ts
  backend/planner-service/docs/README.md
  backend/planner-service/package-lock.json
  backend/planner-service/src/models/TodoList.ts
  backend/planner-service/src/models/TodoTask.ts
  backend/planner-service/src/routes/todoList/todoList.ts
  backend/planner-service/src/routes/todoList/todoTask.ts
  backend/planner-service/src/services/todoList.ts
  backend/planner-service/src/services/todoTask.ts
  frontend/front-end-flutter/planpals/lib/features/home/views/home_page.dart
  frontend/front-end-flutter/planpals/lib/features/profile/services/user_service.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/shopping_list_viewmodel.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/views/shopping_lists_view.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/models/todo_list_model.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/models/todo_list_view.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/models/todo_task_model.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/todo_list_service.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/todo_list_viewmodel.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/components/create_todo_list_form.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/components/create_todo_task_form.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/components/todo_list_card.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/components/todo_task_card.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/components/update_todo_task_form.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/todo_list_details_view.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/todo_lists_view.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/views/planners_view.dart
  frontend/front-end-flutter/planpals/lib/main.dart
  frontend/front-end-flutter/planpals/lib/shared/components/invite_user_dialog.dart
Labels: Task, Feature

#113 Todo list flutter
  backend/planner-service/src/controllers/planner.ts
  backend/planner-service/src/routes/planner/planner.ts
  backend/planner-service/src/services/planner.ts
  frontend/front-end-flutter/planpals/lib/features/home/views/home_page.dart
  frontend/front-end-flutter/planpals/lib/features/profile/services/user_service.dart
  frontend/front-end-flutter/planpals/lib/features/profile/viewmodels/user_viewmodel.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/Shopping_list_service.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/components/create_shopping_list_form.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/components/shopping_item_card.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/shopping_list_viewmodel.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/views/shopping_list_details_view.dart
  frontend/front-end-flutter/planpals/lib/features/shopping_list/views/shopping_lists_view.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/models/todo_task_model.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/todo_list_service.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/todo_list_viewmodel.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/components/todo_task_card.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/todo_list_details_view.dart
  frontend/front-end-flutter/planpals/lib/features/todo_list/views/todo_lists_view.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/models/planner_model.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/services/planner_service.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/viewmodels/planner_viewmodel.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/views/components/Forms/create/create_destination_form.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/views/planner_details_view.dart
  frontend/front-end-flutter/planpals/lib/features/travel_planner/views/planners_view.dart
  frontend/front-end-flutter/planpals/lib/main.dart
  frontend/front-end-flutter/planpals/lib/shared/components/generic_card.dart
  frontend/front-end-flutter/planpals/lib/shared/components/generic_list_view.dart
  frontend/front-end-flutter/planpals/lib/shared/components/invite_user_dialog.dart
  frontend/front-end-flutter/planpals/lib/shared/components/navigator_bar.dart
  frontend/front-end-flutter/planpals/lib/shared/network/api_service.dart
  frontend/front-end-flutter/planpals/lib/shared/styles/app_styles.dart
  frontend/front-end-flutter/planpals/lib/shared/styles/background.dart
Labels: bug, Feature
